### ISSUE TITLE
Neo blocks disappear on save

### ISSUE THREAD

**Issue by SnarkieDesign** [spicywebau/craft-neo#298]
#### Description
This issue took down our production site homepage for a weekend. We were editing a seperate field (not the Neo field and in another tab) before hitting Save, not realising that Neo had not yet loaded and the Blocks had been wiped.

#### Steps to reproduce
1. Load an entry with a large populated Neo field
2. Hit Save immediately before the Neo field loads (on our site, this can take up to 15 seconds as Neo gets pretty slow with a large configuration)
3. The entry has saved and wiped all existing blocks

#### Other information
- Neo version: 2.5.8
- Craft version: Craft Pro 3.3.15
- Is eager-loading used?: No

**Comment by SnarkieDesign** [comment]
Here is a recreation of the issue

![neo-bug](https://user-images.githubusercontent.com/8190792/74692701-4bb4ae80-5238-11ea-9970-8debcada7d9d.gif)

**Comment by chasegiunta** [comment]
I wonder if this is more Craft related. The save button should be disabled until all fields have fully loaded. Then again, with Craft 3.4, something like this has probably already been addressed with Delta updates.

>**Delta entry updates**. Saving complex entries with lots of custom fields and Matrix blocks take a lot less time now, as only the changed values will get submitted and processed.

@SnarkieDesign would it be possible for you to update to 3.4 and try to recreate the issue?

**Comment by pvldigital** [comment]
Hi @SnarkieDesign,

You can updating like @chasegiunta suggested and see if it solves the issue (make sure to test locally first). If not I'm guessing it's something to do with the serialized data that's being sent on save. Once neo has loaded all the blocks it'll update the serialized data of the form but if it hasn't been processed the data will be seen as empty (for neo) which can cause the issue you posted.

I'll have a look and see if there's a way around or I'll disable the save button until everything has loaded.

**Comment by pvldigital** [comment]
Small update: So currently neo uses JS to add all the blocks within the page which is why it's causing the delay and the issue listed. This was how neo always functioned from craft 2 to 3.

To remedy this issue I'll need to rewrite a section of neo so it adds previous blocks directly onto the page without JS. It'll take time to do but i'll keep you updated on the progress.

**Comment by tomdeleu** [comment]
Any news on this? Seems to still happen, and honestly causing a lot of pain when it does.

**Comment by SnarkieDesign** [comment]
We are now running Craft 3.7.15, and I haven't been able to reproduce the problem.

Saving before Neo loads throws an error, without wiping page data. Can't say how or where this was fixed, but I'll close this issue

<img width="582" alt="error" src="https://user-images.githubusercontent.com/8190792/142962417-5c42dd84-9acf-4db6-9aae-62d92e0b6ed9.png">

**Comment by ttempleton** [comment]
Just to update on this issue: as of Neo 3 for Craft 4, the rewrite of how Neo input blocks are rendered has happened, which resolves the original cause of this issue. The blocks disappearing may not have happened on Craft 3.7 due to some changes made in Neo 2.11 for Craft 3.7 compatibility (basically, if no data was sent back to the server for the Neo field, that is interpreted as 'nothing should be changed for this Neo field' instead of 'this Neo field now has no content, delete everything that was there before').
