### ISSUE TITLE
14000 x Updating search indexes 

### ISSUE THREAD

**Issue by JensvdHeydt** [spicywebau/craft-neo#435]
#### Description
Every time a user saves a new page neo is creating around 192 queue entries to update the search index. Having a quite complex neo structure this seems ok but since not a single field in my site is actually marked as to be included into search index I was wondering if this could be lightly optimized.

The queue in my craft installation has currently around 15500 entries and I'd guess round 99% of them are "updating search indexes". How can I prevent this from happening?

#### Steps to reproduce
1.I'm using a single neo field clients are using for content building. I guess there are around 4-5 neo blocks on every page, containing around 2-3 craft fields each.
2.
3.

#### Other information
- Neo version: 2.9.3
- Craft version: 3.6.10
- (if multi-site) What is the affected Neo field's propagation method: all
- Is eager-loading used?

**Comment by JensvdHeydt** [comment]
Would it be possible to introduce a new neo option to disable the search index update when saveElement() is called? Craft CMS introduced a parameter to do so. See: https://github.com/craftcms/cms/issues/5397

**Comment by ttempleton** [comment]
I don't think we need to use the `$updateSearchIndex` parameter; Matrix and Super Table don't use it either and, in my testing, it appears that search index jobs are being generated for a non-searchable Matrix field's blocks, so I'm guessing that's still supposed to happen -- or, if it isn't, then there's likely a Craft bug at play here.

Looking through it, though, I did notice that Neo fields weren't respecting sub-fields' non-searchable settings when generating search keywords, so that has now been fixed in Neo 2.9.4.

**Comment by JensvdHeydt** [comment]
Thanks for the feedback and the bugfix for those sub-fields. I'm still experiencing the described problem though I understand that this could be a substantial problem with craft and how the index is handled, @ttempleton

**Comment by JensvdHeydt** [comment]
@ttempleton I've noticed that I have many jobs in the queue that do not have any fieldHandles. Like this one:

{
    "elementType": "benf\\neo\\elements\\Block",
    "elementId": 156595,
    "siteId": 2,
    "fieldHandles": [],
    "description": null
}

Why would it ne necessary to update the search index for this block if it does not have any fields? I have also noticed that the IDs seem to be rather large. My site has 72 entries with some drafts and versions. I'm sorry to bother you with this. I'm still trying to find a way to optimize my sites queue usage.

**Comment by JensvdHeydt** [comment]
@ttempleton I've noticed that you did some changes and added them to 2.10.0 milestone. That's great news! What are your plans to release that version?

**Comment by ttempleton** [comment]
@JensvdHeydt Hoping to have 2.10 ready for release later this month.

**Comment by ttempleton** [comment]
Just released Neo 2.10.0 which makes this change.  By default, Neo will now only set the search indexes for its blocks to be updated if all of the following conditions apply:

- the Neo field the block type belongs to is searchable
- the block type has a field layout
- the field layout has any searchable sub-fields

I've also added the `optimiseSearchIndexing` plugin setting in case anyone wants to opt out of the optimisations.
