### ISSUE TITLE
TypeError in control panel field settings

### ISSUE THREAD

**Issue by mihob** [spicywebau/craft-neo#523]
#### Description

It is no longer possible to edit Neo type fields. As soon as you open the settings, the following error is thrown:

```
TypeError

craft\web\twig\variables\Cp::field(): Argument #1 ($input) must be of type string, null given, called in /var/www/vendor/twig/twig/src/Extension/CoreExtension.php on line 1511
```

The problem is probably caused by the following craft function:

```
in /var/www/vendor/craftcms/cms/src/web/twig/variables/Cp.phpat line 811
     
     * Renders a field’s HTML, for the given input HTML or a template.
     *
     * @param string $input The input HTML or template path. If passing a template path, it must begin with `template:`.
     * @param array $config
     * @return string
     * @throws TemplateLoaderException if $input begins with `template:` and is followed by an invalid template path
     * @throws InvalidArgumentException if `$config['siteId']` is invalid
     * @since 3.7.24
     */
    public function field(string $input, array $config = []): string
    {
        return CpHelper::fieldHtml($input, $config);
    }

```

While $input is null, $config is filled with the following data:

```
[
        'label' => 'Konfiguration'
        'instructions' => 'Definieren Sie die Blöcke, die in diesem Neo-Feld erstellt werden können, sowie die Felder, aus denen jeder Blocktyp besteht.'
        'name' => 'config'
    ]
```

If I allow null for $input in this function as well as for $input in the function CpHelper::fieldHtml it works again.

#### Steps to reproduce
1. Go to Settings / Fields in Control Panel
2. Open field of type Neo 

#### Other information
- Neo version: 2.11.20
- Craft version: 3.7.24

**Comment by ithic** [comment]
Encountering the same error after upgrading. Attempted to downgrade back to 2.11.19 but still getting the same issue.

**Comment by mihob** [comment]
I think the issue occurs since the last Craft CMS update (3.7.24)

**Comment by brandonkelly** [comment]
Looks like this is the same issue as presseddigital/linkit#92 – something is probably calling the `field()` macro in Craft’s `_includes/forms` template, without passing input HTML in the second argument. Perhaps as a way of outputting a heading.

We have made Craft more defensive for this scenario for the next release (https://github.com/craftcms/cms/commit/85e391000aa64f564bcf6883b6cb207e6db65264), but if Neo is in fact using `field()` to output a heading, it should be fixed in Neo regardless, because `<label>`s are not meant to be used as headings.

**Comment by ttempleton** [comment]
Yeah, the `field()` macro is being used to generate the heading, instructions and empty `.input` element for the block type settings, before the block type settings HTML is inserted using JavaScript, and we do require an empty `.input` for that. I've made a change to the settings template so the error should no longer occur with Neo 2.11.21.

**Comment by henrikhb** [comment]
Running Craft v. 3.7.24 and Neo 2.11.21 this error still occurs when trying to edit a Neo field in the backend

**Comment by siebird** [comment]
I'm getting the same error also with Craft `3.7.24` & Neo `2.11.21`

**Comment by comarko** [comment]
I receive the same error with Craft 3.7.24 & Neo 2.11.21

**Comment by siebird** [comment]
Not exactly what step cured it for me. I was able to fix this by doing the following: 

1. 'rm -rf storage/runtime`
2. `./craft clear-caches/all`
3. `rm -rf vendor/ && rm composer.lock && composer clear-cache && composer install`

**Comment by comarko** [comment]
"./craft clear-caches/all" works for me. Thank you siebird.
