### ISSUE TITLE
Some Blocks Not Recognizing that they have Child Blocks

### ISSUE THREAD

**Issue by brianrivet-tilt** [spicywebau/craft-neo#597]
I am seeing some strange behavior where I have some blocks in my site that don't seem to recognize when they have child blocks. I can add a child, but when I put a tag into my template to return a count of the children, it returns 0 even though there is clearly a child block present in the control panel.

#### Steps to reproduce
1. View the home page entry in the CP. The page section block has two children, and each of those blocks has a child. The block with the issue is the Section Style Adjustments block. It has a child block in it, in the CP, but it is registering 0 children in the templates.
2. If you look at the code in the templates/_boilerplate/_bodyblocks/sections/section.twig template, I have code in lines 54-63 trying to test for the children of the section Style Adjustment block, but the count is returning 0.
Here's the code I mentioned:
`
{{styleAdjusts.type.handle}}
	
	{{styleAdjusts.children.count()}}
	{% for item in styleAdjusts.children.all() %}
		{% if styleAdjusts == null %}
			NULL
		{% else %}
			NOT NULL
		{% endif %}
		{{item.type.handle}}
		{#
		{% set myFields = item.getCustomFields() %}
		{% for fieldItem in myFields %}
			{{fieldItem.handle}}
		{% endfor %}
		#}
	{% endfor %}
`
where the variable styleAdjusts references the Section Style Adjustment block.

3. You can view the output of that code by viewing the home page and inspecting.

#### Other information
- Neo version: 3.0.6
- Craft version: 4.0.4
- (if multi-site) What is the affected Neo field's propagation method: Not multi-site
- Is eager-loading used? yes

I put together a dropbox folder with the templates, project config etc. and a db dump.
https://www.dropbox.com/sh/u4zqp8wsswo8y3d/AAChaFDiByVOg-x-XW7im7Qja?dl=0

**Comment by brianrivet-tilt** [comment]
If there is anything else you need to identify the issue please let me know. I'm still working on it on my end, but no luck so far.

**Comment by brianrivet-tilt** [comment]
FWIW it is happening with multiple different block types. I added a container a style adjustment block to the container that is a child of the section and it showed no children either when I added things to it. It seems like the style adjustment blocks don't show as having children even when I have added them in the cp.

**Comment by brianrivet-tilt** [comment]
I've been able to narrow it down to the block called Style Controls Padding. For some reason, my templates are not recognizing it as a child. I can create different block types that have that as an available child, and if I add that block type to any of those parents, it shows as a child in the control panel, but when I try to output the children in the templates, it is as if the block doesn't exist. So for example, if I add one of each of the 4 different available child block types to the Style Adjustments - Section block, the control panel shows 4 child blocks, but the block.children.count() statement only shows 3 children. 

I've tried deleting the block type and re-creating it, but that had no effect. I'm kind of stumped as to the issue here, so if you can offer any insight on this  I'd appreciate it.

**Comment by ttempleton** [comment]
From a quick look at it, there's some strange stuff happening with the block query where the `typeId` property seems to be set to an array of every valid block type ID, _except_ the Style Controls Padding type ID. Will keep looking into it.

**Comment by brianrivet-tilt** [comment]
I don't know if this helps shed any light or not, but here's some more weird behavior I'm seeing (hopefully not coder error)

I have this block of code that goes through the child blocks of the styleAdjustments block making what should be an array of style control blocks:

`
{% if styleAdjusts != null %}	
	{# add style changes to array except for padding because it isn't applied to primary element #}
	{% for styleItem in styleAdjusts.children.type('not', 'styleControlsPadding', 'styleControlsBackground').all() %}
		{% set styleClasses = styleClasses|merge(styleItem) %}
	{% endfor %}
{% endif %}
`
But, if I try to access the fields or anything from those blocks I get this error:
Impossible to access an attribute ("type") on a integer variable ("29").

Here's the code block that is throwing the error:

`
{% for styleItem in styleAdjusts.children.type('not', 'styleControlsPadding', 'styleControlsBackground').all() %}
		{{styleItem.type.handle}}
	{% endfor %}
	
	{% for styleBlock in styleClasses %}
		{{styleBlock.type.handle}}
	{% endfor %}
`
The first block that uses the query works fine, but the second one that use the styleClasses array returns an error. Am I not understanding this or should those two block return the same thing?

**Comment by ttempleton** [comment]
I missed the line where `styleAdjusts.children.type('not styleControlsPadding')` was being set. That would explain why the `typeId` is set to every type ID except the Style Controls Padding one. Since the later query using `styleAdjusts` is internally using the same live children query as this one that's setting the block type requirements, the Style Controls Padding block isn't appearing. You'd need to resolve that by changing the above to:

```twig
clone(styleAdjusts).children.type('not styleControlsPadding')
```

Regarding the modified version from your previous comment:

```twig
styleAdjusts.children.type('not', 'styleControlsPadding', 'styleControlsBackground')
```

Firstly, that should be passed as an array:

```twig
styleAdjusts.children.type(['not', 'styleControlsPadding', 'styleControlsBackground'])
```

Secondly, passing that in as an array was actually causing a different error due to `type()` not accepting an array when it should have been, so that has now been fixed in Neo 3.0.7.

**Comment by brianrivet-tilt** [comment]
Thanks so much for your help. I knew it had to be something I was doing wrong.

Brian Rivet
***@***.***

**Comment by brianrivet-tilt** [comment]
I'm still seeing an issue here, though admittedly it could be an issue with my code. I have stripped the template code down a bit to try to simplify. I have this line:

`
{% for item in section['children'].all() %}
	{% if item.type.handle == 'childrenSection' %}
		{% set contentKids = item %}
	{% elseif item.type.handle == 'styleAdjustmentsSection' %}
		{% set styleAdjusts = item %}
	{% endif %}
{% endfor %}
`

Based on how I have my Neo field content set up on the home page of the site, there is a single section with two direct children that also have sub children. The two direct children are one of type 'container' and the other is of type 'styleAdjustmentsSection'. I added this line of code to try to verify that the actual Neo blocks are being dropped into those arrays. I added this block below it:

{% for childitem in styleAdjusts.children.all() %}
	{{childitem.type.handle}}
{% endfor %} 

So the code should output the type handle of every child block of the block referenced in styleAdjusts. That block is of type styleAdjustmentsSection and in the control panel it shows 3 children currently, 1 block of type styleControlsType, one of styleControlsPadding, and one of type styleControlsAlignment. When I view the template output from the loop above, it lists only two children, styleControlsType and styleControlsContentAlignment.  The previous line about not styleControlsPAdding has been removed so it should not be affecting anything and it should be puling all three children, correct?

**Comment by ttempleton** [comment]
Yeah, that should be working, and I've made those changes to that file and it does seem to be working for me. Have you made any other changes to other template files that could be relevant? If so, could you please upload them to the Dropbox or email them to plugins@spicyweb.com.au, whichever you prefer.

**Comment by brianrivet-tilt** [comment]
I’ve updated the templates folder in the dropbox link. The only file I’ve been making any adjustments to since I sent the link is the temples/_boilerplate/_bodyblocks/sections/section.twig template. I added a bit of code with a comment. I used the clone statement, it shows 0 children in the styleAdjusts element. If you look at the complete template, the variable styleAdjusts references the child block under section with type styleAdjustmentsSection. In my database currently, if I look at it in the control panel, it has 5 child blocks total, two blocks of type styleControlsType, one of styleControlsContentAlignment, one of styleControlsBackground and one of styleControlsPadding. 

I have the following block of code that is intended to set up an array of the children that are not of class styleControlsPadding not styleControlsBackground, and then two more lines intended to grab the child blocks of each of those types respectively:

 {# create array to collect style changes to primary element #}
{% set styleClasses = [] %}
 {% set padClasses = [] %}
 {% set bgClasses = null %}

         {% if styleAdjusts != null %}	
	{# add style changes to array except for padding because it isn't applied to primary element #}
	
	{% for styleItem in styleAdjusts.children.type(['not', 'styleControlsPadding', 'styleControlsBackground']).all() %}
		{% set styleClasses = styleClasses|merge([styleItem]) %}
	{% endfor %}
	
	{# add separate array to add padding classes since they are applied separately to inner #}
	
	{% for padItem in styleAdjusts.children.type('styleControlsPadding').all() %}
		{% set padClasses = padClasses|merge([padItem]) %}
	{% endfor %}
	
	{# Set variable for background settings if there are any #}
		
		{% for bgItem in styleAdjusts.children.type('styleControlsBackground').all() %}
			{% set bgClasses = bgItem %}
		{% endfor %}
	
{% endif %}


Unless I am misunderstanding what this code should be doing, I would expect that the variable styleClasses would be an array of all of the child blocks under styleAdjusts except for the padding and background ones. bgClasses should be the child that is type styleControlsBackground and padClasses should be the child of type styleContorlsPadding.

I added code to the section template to test this:

{{padClasses|length}}<br>
{{padClasses[0].type.handle}}<br>	
{{bgClasses.type.handle}}<br>
{{ styleAdjusts.children.count() }}
<br>
{{ styleAdjusts.children.type('styleControlsPadding').count() }}
<br>
{% for childblock in styleAdjusts.children.all() %}
	{{childblock.type.handle}}
{% endfor %}


For the padClasses|length statement I get a value of 1 (which is correct)
The padClasses.type.handle statement returns a correct answer as well.
The bgClasses type handle statement returns a correct answer too.

Then the line about styleAdjusts.children.count returns 1. I would think it would return 5 since there are 5 children total in the styleAdjustmentsSection block being referenced by styleAdjust. 

The for loop after that only outputs one type handle for styleControlsPadding. That confuses me too, because again, the loop should be going over all of the children in styleAdjusts and there are 5.

If I take out the code setting bgClasses and padClasses, then I get the following from these lines of code:
 
styleAdjusts.children.count() returns 3, which again isn't the 5 total children, If it isn't counting the padding block and the background block then it would 3, but that's not what the statement is asking for, and I would think that styleAdjusts is the block that contains all of these children, so I'd think it should always return 5 to that statement unless I add something to filter out elements. I suspect this is where my misunderstanding is.

The for loop statement  after that only outputs a single line "styleControlsPadding". That doesn't make sense to me since I would think if it is looping over all of the children of styleAdjusts it should be outputting 3 lines based on the fact that it said the children count was 3 two lines above, but I would have thought it would be have output 5 lines since there should be 5 children.

You mentioned using a clone statement on styleAdjusts. if I do that like this:

{% if styleAdjusts != null %}	
	{# add style changes to array except for padding because it isn't applied to primary element #}
	
	{% for styleItem in clone(styleAdjusts).children.type(['not', 'styleControlsPadding', 'styleControlsBackground']).all() %}
		{% set styleClasses = styleClasses|merge([styleItem]) %}
	{% endfor %}
	
	{# add separate array to add padding classes since they are applied separately to inner #}
	
	{% for padItem in clone(styleAdjusts).children.type('styleControlsPadding').all() %}
		{% set padClasses = padClasses|merge([padItem]) %}
	{% endfor %}
	
	{# Set variable for background settings if there are any #}
		
	{% for bgItem in clone(styleAdjusts).children.type('styleControlsBackground').all() %}
		{% set bgClasses = bgItem %}
	{% endfor %}
	
{% endif %}

Then I get the following output:

styleAdjusts.children.count returns 5 as I would think it would.
styleClasses returns a length of 0, which I would expect it to be 3 since it should be all of the child blocks except the padding and the background.
padClasses also returns a length of 0 which I'd have thought that would be 1.

I may be misusing the clone statement, but I've never needed it with my Neo blocks before, so I'm not sure what it is doing. Can you clarify, or if the output I'm describing isn't what you'd expect either, then there may still be an issue.

Thanks

**Comment by ttempleton** [comment]
Thanks for updating the template. I've given you an incorrect example of `clone` usage above, sorry about that. Instead of e.g. `clone(styleAdjusts).children` it should be `clone(styleAdjusts.children)` (the idea being to clone the child block query itself before applying type parameters etc.)

Arguably, since Craft 4 returns a cloned field value when accessing `someElement.someFieldValue`, memoized Neo child block queries should do the same for consistency, but I'm concerned that could be considered a breaking change at this point.

**Comment by brianrivet-tilt** [comment]
The correction to the clone statement fixed the problem I was having. Thanks for your your help!

Brian Rivet
***@***.***

**Comment by brianrivet-tilt** [comment]
Hi Thomas, I’m still seeing similar problems if I nest elements further down.

I’ve updated the database and template folders on Dropbox. Basically, I added a block called a Container 2 column to the home page. It has two possible children, a children2ColumnContainer, and a styleAdjustmentsContainer2Column. I added a styleAdjsutmentsContainer2Column to the block, and it can possibly have these children:

styleControlsPadding
styleControlsBackground
styleAdjustmentsRow

The padding and background blocks work fine. The AdjustmentsRow one is giving me trouble this time. It is able to have children as well, which are what I am trying to access. I put in this code to basically do what I was doing with the pads, etc. with this block:

{% set rowClasses = [] %}
{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').all() %}
{% if rowAdjusts is not empty %}
	{% for rowItem in clone(rowAdjusts.children).collect() %}
		{% set rowClasses = rowClasses|merge([rowItem]) %}
	{% endfor %}
{% endif %}

This code gives me this error:

Key "children" for array with keys "11" does not exist.

Coming from the line:

{% for rowItem in clone(rowAdjusts.children).collect() %}


I then replaced the code with this to see what rowAdjusts actually is:

{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').all() %}
	{% for key, value in rowAdjusts %}
		{{key}} : {{value}}
	{% endfor %}

And that output:

11: 539

If I change the line where I set rowAdjsuts to a collect() instead of an all() I get:

Method Illuminate\Support\Collection::children does not exist.

Which I assume is due to it being a collection and not having the children property. Can you tell me how I can set this up because I will have a few children under the styleAdjsuts from time to time that will have children I need to access instead of just working directly with their fields.

Thanks,

Brian Rivet
***@***.***

**Comment by ttempleton** [comment]
From the block type settings, it looks like you're only expecting a single block of type `styleAdjustmentsRow` to exist under the parent block, so it should be fine to call `one()` there instead of `all()` when setting `rowAdjusts`.

**Comment by brianrivet-tilt** [comment]
I’ve adjusted the code to this:

{% set rowAdjusts = styleAdjusts.children.type('styleAdjustmentsRow').all() %}
{% if rowAdjusts is not empty %}
	{% for rowItem in clone(rowAdjusts.children).collect() %}
		{% set rowClasses = rowClasses|merge([rowItem]) %}
	{% endfor %}
{% endif %}

But I get this error:

Key "children" for array with keys "9" does not exist.

**Comment by brianrivet-tilt** [comment]
I’ve also tried:

{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').all() %}

And 

{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').all() %}
{% if rowAdjusts is not empty %}
	{% for rowItem in rowAdjusts.children.all() %}
		{% set rowClasses = rowClasses|merge([rowItem]) %}
	{% endfor %}
{% endif %}

And 

{% set rowAdjusts = styleAdjusts.children.type('styleAdjustmentsRow').all() %}
{% if rowAdjusts is not empty %}
	{% for rowItem in rowAdjusts.children.all() %}
		{% set rowClasses = rowClasses|merge([rowItem]) %}
	{% endfor %}
{% endif %}

But they all return that same error.

**Comment by ttempleton** [comment]
Change the line

```twig
{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').all() %}
```

to

```twig
{% set rowAdjusts = clone(styleAdjusts.children).type('styleAdjustmentsRow').one() %}
```

and that should work.

**Comment by ttempleton** [comment]
Change any cases of `clone(styleAdjusts).children.all()` to `clone(styleAdjusts.children).all()` and see if that works. If it doesn't, please upgrade Neo to the latest version and let me know if that works.

**Comment by brianrivet-tilt** [comment]
Will do. I think I’m good with regard to this issue. I did submit a new one the other day regarding a UI issue I’m seeing, but you can address that one whenever you see fit.
