### ISSUE TITLE
Entry content disappears within CP

### ISSUE THREAD

**Issue by superflausch** [spicywebau/craft-neo#91]
We have an issue on on of our clients website where NEO blocks started to disappear and only the first block is shown within the CP entries pages. When I check the rendered pages or the DB directly, the content is still there.

Maybe this is also related to [issue #81](https://github.com/benjamminf/craft-neo/issues/81).

I see the following JS error in my console:

```
Uncaught TypeError: Cannot read property 'children' of undefined
    at proto.constructor._updateBlockChildren (Input.js:346)
    at proto.constructor.addBlock (Input.js:213)
    at proto.constructor.init (Input.js:148)
    at proto.constructor.constructor (garnish.js:705)
    at proto.constructor (garnish.js:40)
    at new proto.constructor (garnish.js:40)
    at de:2122
```

I just checked and we are running the latest build from the master branch.

Any ideas? Let me know if I can provide additional info. This is an urgent issue for us. Thanks a lot.

**Comment by superflausch** [comment]
I just noticed that we had an old JS error coming from an other plugin. Deactivating the other plugin resolved the issue. Strangely this error/issue never affected the display of the NEO blocks until today. Not sure what changed, next to additional content added by the client, what could cause this new behaviour.

As our issue is resolved for now we can close this issue here. I will just leave it for now as this maybe is something which could also be solved/caught on NEO side. Up to you. Thanks for the effort and an awesome plugin.

**Comment by benjamminf** [comment]
Neo renders it's fields entirely with Javascript. This is in order to keep the codebase DRY, which in turn makes things more reliable (in a sense). Unfortunately if a JS error happens before the Neo field is initialised, then the JS stops executing and the Neo field doesn't render. Since I can't guarantee the order of JS in the control panel I can't do a whole lot about it.

An idea could be to pre-render an error/warning message in place of Neo's blocks that will only show if the JS isn't run. Not the ideal solution but it'll be easier to troubleshoot when things go wrong.

**Comment by camerondway** [comment]
Any update on a fix for this?

**Comment by m8brgarc** [comment]
Hey, I'm still having issues with this.  For some reason, content randomly disappears from my entries (It's only the neo field that completely disappears)  then I need to select an earlier version to get my content back.  I checked to make sure no one was randomly deleting the content and it doesn't look like any updates were made to the entry for a long while.

So I'm not sure what is going on.  Can I get some help with this?  I'm not even sure if this is the exact same issue as this one.

**Comment by pvldigital** [comment]
Hi @m8brgarc,

What version of Craft and neo are you using? This issue was for craft 2 which is not supported anymore.

**Comment by ttempleton** [comment]
The next Neo release (which will probably be version 2.7.20) will display a spinner on Neo fields before their contents load.  Our overall goal to resolve situations such as this is to move the rendering of existing field content out of the JavaScript, as has been more recently described in #298, so at this point I'll close this issue in favour of that one.
