### ISSUE TITLE
Lost some data and content after upgrading from Craft 4 to Craft 5

### ISSUE THREAD

**Issue by bhashkar007** [spicywebau/craft-neo#943]
### Bug Description

I had built a website using Craft 2.6.3019 several years ago and Neo field is widely used with the combination of Matrix field. Now we are planning to upgrade it to Craft 5 (latest version). So I did:
- Upgrade from Craft 2 to Craft 3 (successful - everything is fine.)
- Upgrade from Craft 3 to Craft 4 (successful - everything is fine).
- Upgrade from Craft 4 to Craft 5 (latest version Craft 5.4.2, Neo 5.2.5) - Upgrade and migration went successful but while checking entries Craft 5 website, I found that data/content of some fields were lost. 

Please help for it.

### Steps to reproduce

- Upgrade Craft 4 to Craft 5 using Neo

### Neo version

5.2.5

### Craft CMS version

5.4.2

### Does this issue involve templating, and if so, is eager-loading used?

This is not a templating issue

**Comment by LinneaHarts** [comment]
This is happening to me too, just in an upgrade from 4 to 5. And it was working before, so I think a new neo upgrade may have done it.

**Comment by LinneaHarts** [comment]
I pinned my neo to 5.2.2 and re-upgraded and it seems to have fixed the problem at least so I can go forward with my upgrade

**Comment by bhashkar007** [comment]
@LinneaHarts It didn't work for me. I re-upgraed from Craft 4 to Craft 5 with Neo v5.2.2 and still having same problem.

**Comment by ttempleton** [comment]
Are there any particular field types that are losing content?

**Comment by LinneaHarts** [comment]
EDIT: sorry, complete different issue

**Comment by bhashkar007** [comment]
Thank you, @ttempleton I found this issue in entries of different sections basically with the field types like:
- Plain Text
- Plain Text (multiline)
- CKEditor (which is migrated from Redactor)
I am afraid that there may be other field types also. It's something large website with 4k+ entries and 14 languages (sites). Please share your thoughts,

**Comment by ttempleton** [comment]
If possible, could you please send both your Craft 4 and 5 composer.json/lock files, and your Craft 4 database backup (so I can see the expected content on Craft 4 and then attempt the upgrade to see where the content is being lost) to plugins@spicyweb.com.au, and we'll have a look.

**Comment by navneetshukla9** [comment]
@bhashkar007  I have also faced the same issue, It gets fixed when you just re-save the field again from Settings->Fields.

**Comment by daveguillory** [comment]
Confirming that I also had the same issue, specifically with CKE fields, and it was resolved by following @navneetshukla9's suggestion of re-saving each Neo field in Settings->Fields.

**Comment by ttempleton** [comment]
[My above request](https://github.com/spicywebau/craft-neo/issues/943#issuecomment-2376724140) remains open for anyone experiencing this.

**Comment by pkluivers** [comment]
We are encountering the same issue. We upgraded two Craft 4 websites that use the Neo plugin to Craft 5. In both cases, the data from the main Neo matrix block has disappeared.

**Comment by ttempleton** [comment]
Still unable to reproduce this - I did a bunch of upgrades from the latest Craft/Neo 4 to 5 yesterday, without any content loss.

[My above request](https://github.com/spicywebau/craft-neo/issues/943#issuecomment-2376724140) remains open for anyone experiencing this.

We are unlikely to be able to fix any issue here until someone fulfils the request.

**Comment by pkluivers** [comment]
I've figured out what happened. It seems that some entries or sections on the website have a hiccup after the Craft 5 update with migrations and all. When I find a section with content pages where some content is missing, I run the command:

`php craft resave/entries --section=sectionName
`
This re-saves all the entries in that section, restoring the missing content.

**Comment by ttempleton** [comment]
We accidentally reproduced the content loss on upgrade to Craft 5 yesterday - it turned out all the missing content was still in the database, but there was somehow a field layout element UUID mismatch between environments. I'm going to try to figure that out asap.

**Comment by ttempleton** [comment]
In our case, it turned out that the affected block types were quite old, and the field layout element data was still in the `fieldlayoutfields` table instead of the `elements` column of the `fieldlayouttabs` table. I have no idea how that happened, but apparently field layout elements get assigned new UUIDs when that happens, and that lead to the field layout element UUID mismatch between environments.

We've just released 3.10.0 and 4.4.0 for Craft 4, which both add the `php craft neo/block-types/resave` console command. This will force the field layout element data into the `elements` column of the `fieldlayouttabs` table, and also regenerate field layout element UUIDs for the affected block types in the project config.

When upgrading to Craft 5, the general process following the [official Craft 5 upgrade guide](https://craftcms.com/docs/5.x/upgrade.html) will be:

- Follow the guide up to the step _before_ the first deployment of project config changes to your live environment
- Run `php craft neo/block-types/resave`
- Deploy your project config changes and follow the rest of the guide

If anyone still has this issue after following the above, please let me know and I'll reopen.

**Comment by romainpoirier** [comment]
I’m also experiencing this issue when upgrading:

* Craft CMS: **4.4.14 → 5.8.20**
* Neo: **4.4.0 → 5.5.3**

After the upgrade, everything looks fine at first, but as soon as I merge another branch that’s on the same Craft/Neo versions and then run:

```bash
php craft project-config/apply
```

I lose all Neo text content.

I’ve tried running:

```bash
php craft neo/block-types/resave
```

and manually resaving each Neo field before doing this, but it doesn’t resolve the issue.

Any help or guidance would be hugely appreciated, as I need to go live in production as soon as possible.

**Comment by ttempleton** [comment]
@romainpoirier if you try the command from https://github.com/spicywebau/craft-neo/issues/943#issuecomment-2642894944:

`php craft resave/entries --section=sectionName`

Does that resolve the issue?

If not, could you please send your Composer files, and your database backup from before running `project-config/apply`, to plugins@spicyweb.com.au if possible, and we'll have a look into it.

**Comment by romainpoirier** [comment]
Unfortunately, this command didn’t resolve the issue.

I’ve realized the problem isn’t limited to my Neo fields but affects all content. My usual workflow is: update the site, then import the production database. At that point, all content is present. However, after the next project-config sync, once I apply the changes, all content disappears.

This seems related to Craft losing track of some field UIDs (some appear to have been regenerated during a migration). As a workaround, I manually diffed the project config files and only merged in the new or updated fields without changing any existing UIDs. It’s tedious, but it does restore the content.

**Comment by ttempleton** [comment]
That's odd, but glad that you could still restore the content.

**Comment by garrill** [comment]
I came across this issue on a Craft 4 site I was updating this week. I queried the database and found I had both a valid set of JSON field layouts in `fieldlayouttabs.elements` and old copies of the same layout defined in `fieldlayoutfields`. I removed the old copies by running the MYSQL command
```mysql
DELETE FROM fieldlayoutfields
WHERE layoutId IN (
    SELECT fieldLayoutId
    FROM neoblocktypes
    WHERE fieldLayoutId IS NOT NULL
);
```
and I was able to see the fields in the CMS again.
